apiVersion: v1
kind: Service
metadata:
  name: legacy
  namespace: edge
spec:
  ports:
  - nodePort: 32080
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: legacy
  type: NodePort
