apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: processor
  template:
    metadata:
      labels:
        app: processor
    spec:
      containers:
      - image: nginxdemos/hello
        name: processor
        ports:
        - containerPort: 80
