apiVersion: apps/v1
kind: Deployment
metadata:
  name: sender
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sender
  template:
    metadata:
      labels:
        app: sender
    spec:
      containers:
      - image: nginxdemos/hello
        name: sender
        ports:
        - containerPort: 80
