apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: legacy-hpa
  namespace: legacy
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: legacy
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
